### ISSUE TITLE
Agent disconnected

### ISSUE THREAD

**Issue by michmoor0725** [openappsec/openappsec#196]
Checking in on my appsec instllation via the portal i noticed that i have no agent connected. Odd. Started digging around best i could and any logs regarding attempted intrusions, etc. stopped on Oct 10.
Digging around a bit more i see the following showing up in the :/data/compose/47/appsec-logs folder

For background this is a NGINX Proxy Manager + OpenAppsec stack.  I think this may be why my agent is disconnected but i really don't know. Looking for ideas

`[2024-10-14T02:25:48@register] Service '/etc/cp/HttpTransactionHandler/cp-nano-http-transaction-handler' already registered with 2 instances for family ''
[2024-10-14T02:26:15@register] enter
[2024-10-14T02:26:15@register] Service '/etc/cp/HttpTransactionHandler/cp-nano-http-transaction-handler' already registered with 2 instances for family ''
[2024-10-14T02:26:49@register] enter
[2024-10-14T02:26:49@register] Service '/etc/cp/HttpTransactionHandler/cp-nano-http-transaction-handler' already registered with 2 instances for family ''
[2024-10-14T02:27:16@register] enter
[2024-10-14T02:27:16@register] Service '/etc/cp/HttpTransactionHandler/cp-nano-http-transaction-handler' already registered with 2 instances for family ''
[2024-10-14T02:27:16@register] enter
[2024-10-14T02:27:16@register] Service '/etc/cp/HttpTransactionHandler/cp-nano-http-transaction-handler' already registered with 2 instances for family ''
[2024-10-14T02:27:50@register] enter
[2024-10-14T02:27:50@register] Service '/etc/cp/HttpTransactionHandler/cp-nano-http-transaction-handler' already registered with 2 instances for family ''
[2024-10-14T02:28:16@register] enter
[2024-10-14T02:28:16@register] Service '/etc/cp/HttpTransactionHandler/cp-nano-http-transaction-handler' already registered with 2 instances for family ''
^C
`

**Comment by orianelou** [comment]
Hi @michmoor0725, 

Can you please run the following command open-appsec-ctl -s from the agent container and share the output? Is the agent still enforcing policy (preventing / detecting)? Also, can you please verify the agent has connection to our Fog at:

- https://inext-agents.cloud.ngen.checkpoint.com
- https://downloads.openappsec.io

Thank you!

**Comment by michmoor0725** [comment]
Thanks for the response. Here is the output. Agent is not enforcing any policy
Your first link brings me to a 403 Forbidden

`
3830b58601a0:/# open-appsec-ctl -s
---- open-appsec Nano Agent ----
Version: 1.1.18-open-source
Status: Running
AI model version: Advanced model V1.0
Management mode: Cloud management (Fully managed)
Agent ID: 018c5c96-c4d6-4d9a-80b1-60356a90e6a9
Profile ID: eec8173a-8059-22f2-5677-94f4d0d2382a
Policy version: 29
Policy load status: Error
Last policy update: 2024-09-16T15:22:32.902831

---- open-appsec Orchestration Nano Service ----
Type: Public, Version: 1.1.18-open-source, Created at: 2024-09-30T15:22:02+0000
Status: Running

---- open-appsec Attachment Registrator Nano Service ----
Type: Public, Version: 1.1.18-open-source, Created at: 2024-09-30T15:22:02+0000
Status: Running

---- open-appsec Http Transaction Handler Nano Service ----
Type: Public, Version: 1.1.18-open-source, Created at: 2024-09-30T15:22:02+0000
Registered Instances: 2
Status: Running


For release notes and known limitations check: https://docs.openappsec.io/release-notes
For troubleshooting and support: https://openappsec.io/support
`

**Comment by orianelou** [comment]
Hi @michmoor0725, 

My apologies for the delay in response, if they issue is still happening can you please reopen the issue, and provide us with your tenant ID? can also be done via email at info@openappsec.io

**Comment by jbeckman1974** [comment]
I have a similar issue.  The agent and ngingx-proxy-manager are both installed.  It shows `Policy load status: Error` just like above, below is the results of my `open-appsec-ctl -s` run from within the container.

```
AI model version: Advanced model V2.0
Management mode: Local management
Agent ID: a3610deb-3bdc-4dca-9267-672286e916d2
Policy files: 
    /etc/cp/conf/local_policy.yaml
Policy load status: Error
Last policy update: 2025-01-06T01:20:40.244286

---- open-appsec Orchestration Nano Service ----
Type: Public, Version: 1.1.21-open-source, Created at: 2025-01-02T10:58:11+0000
Status: Running

---- open-appsec Attachment Registrator Nano Service ----
Type: Public, Version: 1.1.21-open-source, Created at: 2025-01-02T10:58:11+0000
Status: Running

---- open-appsec Http Transaction Handler Nano Service ----
Type: Public, Version: 1.1.21-open-source, Created at: 2025-01-02T10:58:11+0000
Registered Instances: 16
Status: Running
```




My compose file.  I spent 10-minutes trying to find where I found this from, but all the stuff I found online and on github didn't match, so maybe I jacked it up?  I wanted to manage it locally but use the online to view things:
```
version: '3.3'
# docker compose for npm open-appsec integration

services:
  appsec-npm:
    container_name: npm-attachment
    image: 'ghcr.io/openappsec/nginx-proxy-manager-attachment:latest'
    ipc: host
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - /var/lib/docker/volumes/nginx_proxy/data:/data
      - /var/lib/docker/volumes/nginx_proxy/letsencrypt:/etc/letsencrypt
      - /var/lib/docker/volumes/nginx_proxy/appsec/logs:/ext/appsec-logs
      - /var/lib/docker/volumes/nginx_proxy/appsec/localconfig:/ext/appsec
    environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      DB_SQLITE_FILE: "/data/database.sqlite"

  appsec-agent:
    container_name: appsec-agent
    image: 'ghcr.io/openappsec/agent:latest'
    network_mode: service:appsec-npm
    ipc: host
    restart: unless-stopped
    environment:
      # adjust with your own email below
      - registered_server='<server name>'
      - user_email='<email I used on my.openappsec.io>'
      - AGENT_TOKEN='<token from Profiles tab>'
      - nginxproxymanager=true
      - autoPolicyLoad=true
    volumes:
      - /var/lib/docker/volumes/nginx_proxy/appsec/config:/etc/cp/conf
      - /var/lib/docker/volumes/nginx_proxy/appsec/data:/etc/cp/data
      - /var/lib/docker/volumes/nginx_proxy/appsec/logs:/var/log/nano_agent
      - /var/lib/docker/volumes/nginx_proxy/appsec/localconfig:/ext/appsec
      - /var/lib/docker/volumes/nginx_proxy/appsec/open-appsec-advanced-model.tgz:/advanced-model/open-appsec-advanced-model.tgz
    command: /cp-nano-agent --standalone
```

**Comment by orianelou** [comment]
Hi @michmoor0725 and @jbeckman1974,

Thank you both for bringing up these issues. It seems they are different in nature, as @michmoor0725 mentioned a problem with disconnecting from the Web UI, while @jbeckman1974 described a local deployment that couldn’t connect.

@michmoor0725, I sincerely apologize again for the delay in our earlier response. As mentioned before, we’ll need the tenant ID from the Web UI to investigate further. Could you kindly send it to us at info@openappsec.io? Additionally, please let us know if the issue persists and whether you’ve tried redeploying since.

@jbeckman1974, regarding your issue, I’ve deployed your compose setup and didn’t encounter any problems. Could you please share the policy you’ve used? Also, if this isn’t your first deployment, could you verify that the volumes mounted to the agents are empty? This might help pinpoint the issue.

Looking forward to your updates so we can assist further!

**Comment by jbeckman1974** [comment]
@orianelou Thank you for the reply.  I was able to figure it out by your post.  You mentioned "the volumes mounted to the agents are empty?".  They were empty, and I created the container but _originally I planned to use the local only option and did not have the `AGENT_TOKEN` tag_.  I added it after-the-fact and this means when I added the token the folders were not empty.  So, I decided to take my `/var/lib/docker/volumes/nginx_proxy/appsec/` folder and delete it.  I stopped the appsec-agent container, deleted and remade the folders blank, and when I restarted it everything worked.  So I am up and working.  To anyone else who started with local and then wanted to go cloud, the answer is to clear out the agent directories.  I did not clear out my nginx-proxy-manager folders, and in fact it appears to remember the settings I had on my 11 hosts (not all were set the same).

SO - thank you.  I am _just_ a self-hoster and have used nginx-proxy-manager for a while by itself but have wanted a WAF.  I played with crowdsec but it was a bit too much for this hobbyist to really manage.  I am very appreciative of you guys who open your commercial products and allow us hobbyist to use it free.  And the fact you replied to me, a free user, is amazing.  Again, thank you.

@michmoor0725 I understand your frustration.  I'm not prone to giving unsolicited advice, but I feel here I must.  The help we asked for wasn't paid help.  It was asking someone for free, so with that in mind be kind.

**Comment by ByteSkater** [comment]
Hi, I want to provide some explanation here about the currently available open-appsec images for NPM integration:

"nginx-proxy-manager-attachment" image:
This is the NPM image with open-appsec-enhanced WebUI for also allowing you to activate and configure open-appsec from same NPM WebUI, view open-appsec security logs, etc. Changes made in the NPM WebUI for open-appsec config will then be reflected in the local_policy.yaml declarative configuration file which the open-appsec agent applies automatically. 
When using this image you could also add a token for the open-appsec WebUI so you can see the open-appsec configuration represented there (read-only) and send e.g logs additionally to the open-appsec WebUI (which provides more flexible logging/monitoring options), but this ONLY makes sense with open-appsec deployment profile in open-appsec WebUI being set to "Declarative configuration - using open-appsec configuration file".

"nginx-proxy-manager-centrally-managed-attachment" image:
This is the NPM image which does NOT include the open-appsec specific WebUI enhancements for the NPM WebUI, but contains our "attachment" in the NPM image so that traffic passing through NPM's NGINX can be inspected by the open-appsec agent.
This image is meant to be used if you want to CENTRALLY manage the open-appsec WAF which protects your NPM from the open-appsec WebUI (SaaS) instead of managing it locally from the NPM WebUI, so this is typically being used with open-appsec deployment profiles in open-appsec WebUI set to mode "This management".

In the open-appsec docs you find separate docker compose files for both deployment/management options. They are very similar, but e.g. some volume mounts (appsec-logs and appsec-localconfig) are not required for the centrally managed image and also the autoPolicyLoad activation (meant for declarative local configuration) is not required in centrally managed deployment.

When having a token configured for open-appsec you can check the management mode easily via "open-appsec-ctl -s" and check what's shown for "Management mode:" 

If you have any additional questions or need technical assistance you can also contact the open-appsec team directly via info@openappsec.io.
