### ISSUE TITLE
Question regarding Python 2/3 compatibility

### ISSUE THREAD

**Issue by ms217** [openappsec/openappsec#20]
While working on a .spec file for EL8 I've stumbled upon across issues with Python compatibility.  

The graphqlparser (external/graphqlparser/CMakeLists.txt:10) seems to require Python 3 while nodes/packaging.cmake seems to expect > Python 2, because when building with Python 2, cmake aborts with message "string sub-command STRIP requires two arguments."

Can I just patch external/graphqlparser/CMakeLists.txt to look for Python 3 interpreter?

Edit
Ended up using Python 2 and fixed the STRIP line in nodes/packaging.cmake by wrapping quotation marks around the ${PACKAGE_VERSION}" var.

However, is it planned to migrate to Python 3, because Python 2 is obviously deprecated?!

**Comment by WrightNed** [comment]
Hi,

We've noticed the Python 2 issue as well and are working to remove this dependency. We expected to be removed within the next two weeks.

Thanks,
Ned

**Comment by WrightNed** [comment]
Hi ms217,

You are right that there is an assumption that the building and installing of open-appsec are done separately - Docker images being the prime example for that.
You can install open-appsec manually as described in the [open-appsec Installation](https://github.com/openappsec/openappsec#open-appsec-installation) section, just use the package you compile locally instead of the downloaded ones and notice that you'll need to install the attachment as well.

I don't have a specific timeline for adding the ability to installing locally through CMake - but if you think that will be a valuable ability for you, I can try to make it happen sooner.

Thanks!

**Comment by ms217** [comment]
Hi Ned,

it would make packaging as an RPM definitely easier for me, but that is just me speaking.
Either way, thank you for listening to my feedback :-)

**Comment by orianelou** [comment]
Hi, 

The issue with Python compatibility is now resolved. 

Thank you, and have a great day,

Oriane
