### ISSUE TITLE
Crowdsec activation blocks all communication

### ISSUE THREAD

**Issue by Flyingfufu** [openappsec/openappsec#202]
Hi,

I try to add Crowdsec in my configuration. If all seems to start well (no error messages), I cannot open any application properly upon start.

Once AppSec Agent, Crowdsec and SWAG have started, Authelia (all on the same docker network) start to throw the following error (here only a short extract):
`....
2024-11-10T20:45:38+01:00 ERR | error=read tcp 172.29.20.5:9091->172.29.20.13:52588: i/o timeout method=GET msg=Request timeout occurred while handling request from client. path=/ remote_ip=172.29.20.13 status_code=408
2024-11-10T20:45:39+01:00 ERR | error=read tcp 172.29.20.5:9091->172.29.20.13:52590: i/o timeout method=GET msg=Request timeout occurred while handling request from client. path=/ remote_ip=172.29.20.13 status_code=408
2024-11-10T20:45:40+01:00 ERR | error=read tcp 172.29.20.5:9091->172.29.20.13:52592: i/o timeout method=GET msg=Request timeout occurred while handling request from client. path=/ remote_ip=172.29.20.13 status_code=408
...
`
172.29.20.5 is my Authelia instance while 172.29.20.13 is SWAG.

While this happens, the SWAG error log is registering the following error (again, only a short extract)
`...
2024/11/10 20:45:49 [error] 1659#1659: *270 auth request unexpected status: 408 while sending to client, client: 192.168.1.254, server: redacted.*, request: "GET /redacted", host: "redacted", referrer: "https://redacted/redacted"
2024/11/10 20:45:49 [error] 1659#1659: *270 auth request unexpected status: 408 while sending to client, client: 192.168.1.254, server: redacted.*, request: "redacted", host: "redacted", referrer: "https://redacted/redacted"
2024/11/10 20:45:49 [error] 1659#1659: *270 auth request unexpected status: 408 while sending to client, client: 192.168.1.254, server: redacted.*, request: "redacted", host: "redacted", referrer: "https://redacted/redacted"
...
`

For the sake of clarity, the decision list is empty.

Stopping Crowdsec container doesn't help. To get all back to normal, I have to remove all .env line in the appsec-agent container.

I'm running out of idea, any idea will be welcome

**Comment by orianelou** [comment]
Hi,

Thank you for reaching out! It sounds like the interaction between the open-appsec agent, Crowdsec, Authelia, and SWAG might be causing network-related issues, especially the I/O timeouts. Here are some steps and suggestions to help troubleshoot:

### Network Configuration:

The timeout errors from Authelia usually indicate a delay or failure in communication with SWAG over the Docker network. To rule out network issues, you might want to inspect your Docker network settings:
Run docker network inspect <network-name> to verify there aren’t any conflicting settings that could be causing timeouts.
Try adjusting the timeout settings in SWAG or Authelia to allow more time for requests between them.
### Resource Allocation:

Running the open-appsec agent and Crowdsec together might lead to high resource usage, impacting other services. You can check resource usage with docker stats to see if either service is consuming excessive CPU or memory.
If this is the case, try setting CPU and memory limits for the open-appsec agent and Crowdsec in your docker-compose.yml.
### open-appsec Configuration:

Since removing .env variables for the open-appsec agent temporarily resolves the issue, some of the environment settings could be impacting network communication.
Review the .env file for network-related configurations and verify they don’t conflict with Authelia or SWAG settings. You might also want to try adding exceptions in open-appsec for the IPs of Authelia and SWAG.
### Crowdsec Settings:

Although your Crowdsec decision list is empty, it may still be inspecting or modifying traffic. If possible, test Crowdsec in a passive mode (if available) to observe if it minimizes interference.
### Isolation Testing:

To identify the cause, you could try starting just Authelia and SWAG, and then adding the other services (first open-appsec, then Crowdsec) to see if the issue reappears.

Let us know if these steps help or if further configuration details are needed. We’re here to help!

**Comment by Flyingfufu** [comment]
Hi there,

Network looks good. Tried also after setting fix ip to each container, but same behaviour. All good with Crowdsec env variable removed from the appsec agent compose but screwing all up when activated.

Ressource allocation doesn't seem to be an issue. If the appsec agent is consuming more once Crowdsec is linked (especially network RX ressource), it is far away from the limit for CPU or memory.

Not sure how to test Crowdsec in passive mode, but will further dig into that

The .env screwing up things in the appsec agent are only the one related to Crowdsec:
`CROWDSEC_ENABLED=true
CROWDSEC_MODE=prevent
CROWDSEC_LOGGING=enabled
CROWDSEC_API_URL=http://crowdsec_appsec:8080/v1/decisions/stream
CROWDSEC_AUTH_METHOD=apikey
CROWDSEC_AUTH_DATA=REDACTED`
As soon those are out of the equation, all is running fine !

**Comment by Flyingfufu** [comment]
Any feedback idea following my last post info ?

**Comment by orianelou** [comment]
Hi @Flyingfufu,

Apologies for the delayed reply! Did testing CrowdSec in detect mode (by setting CROWDSEC_MODE=detect) help? Also, have you tried running CrowdSec without open-appsec? This will help us determine whether the issue lies with the open-appsec + CrowdSec integration or with the deployment of CrowdSec itself.

Looking forward to your feedback!

**Comment by Flyingfufu** [comment]
Hi @orianelou 

Running all with CROWDSEC_MODE set to "detect" doesn't change the result. All get suddenly so slow that nothing is usable.
As mentionned earlier, stopping the Crowdsec container is of no help.
Also tested with loggin enabled or disabled, but same bad result.
However, changing CROWDSEC_ENABLED to false is getting everything running smoothly again, even keeping the Crowdsec container running.

Just to be sure : I have CROWDSEC_API_URL=http://crowdsec_appsec:8080/v1/decisions/stream. Is this correct ? At least looking in the Crowdsec logging it looks like being communicating well between the 2 containers.

An alternate installation with the  sandard SWAG and Crowdsec containers is just running fine.

**Comment by orianelou** [comment]
Hi @Flyingfufu 

Thanks for the detailed feedback!
Regarding the URL The CROWDSEC_API_URL=http://crowdsec_appsec:8080/v1/decisions/stream appears to be correct if the CrowdSec LAPI is accessible at that address and port. You mentioned that the logs indicate communication between the two containers, and that this work with SWAG which confirms this is likely set up correctly. of course if with the SWAG deployment a different URL is used this could be the issue. 

Regarding how to retrive this URL, in most installations, the CrowdSec LAPI URL is defined during setup. If you deployed CrowdSec using Docker Compose, check the service configurations (docker-compose.yml) for the LAPI URL.

If you deployed CrowdSec on a dedicated server or VM, the default LAPI URL is typically http://<host-ip>:8080/v1/decisions/stream. Replace <host-ip> with your server's IP address or hostname.
You can also vrify the API settings in CrowdSec's local_api_credentials.yaml file, which includes the base URL and port used by the LAPI.
