### ISSUE TITLE
Blocking my web admin access

### ISSUE THREAD

**Issue by siilitman** [openappsec/openappsec#54]
We are running nginx stable 1.24.0 and I have the openappsec agent connected into the SAAS interface.
Within the web interface, I've setup a Profile and and managing the agent policy through the interface.
The agent was installed on the 14 Sep
I've setup an asset with the site url's, added trusted sources for our two main public IP's + our dev's IP and it's reached graduate learning level.
When ever I flip the asset from Learn/Detect to protect, the next time our dev tries to access the admin back end and edit things, it's blocking him with a Cross Site Scripting/ SQL injection incident type.
I'm then right clicking on the event and creating an exception but I'm on double figures now for the exceptions. Exception examples are below....

Source Identifier : xxx Trusted IP xxx
URI : /xxx/admin/dashboard/
Parameter Name : s_sq..old
Paramter Value : .*

Source Identifier : xxx Trusted IP xxx
URI : /xxx/admin/import/
Parameter Name : s_sq..old
Paramter Value : .*

How can I stop my dev getting blocked?

**Comment by orianelou** [comment]
Hi @siilitman,

Have you modified the agent to use our [advanced machine-learning model](https://docs.openappsec.io/getting-started/using-the-advanced-machine-learning-model)? Also, could you please send us your tenant ID to the info@openappsec.io email? We'll look into this. 
![image](https://github.com/openappsec/openappsec/assets/126462046/947e7a97-0087-449b-b6ea-59a323b42b84)

**Comment by siilitman** [comment]
I completely missed the advanced ML model. I've sent the tenant ID and will download the new ML model to give that a try.

Thanks

**Comment by orianelou** [comment]
Hi @siilitman, 

Thank you for the swift response! We'll look into it. As to the Advance Model, there's no need to download the ML model until we've identified your current issue,  we just wanted to know more about your deployment.

Thanks, and hope to update you soon, 

Oriane

**Comment by orianelou** [comment]
Hi @siilitman,

We've pinpointed the issue: the WAF only learns when there are at least "Minimum users to trust:" trusted sources engaging in the same activity. Since you only have one Dev IP, it hasn't had the opportunity to learn.
![image](https://github.com/openappsec/openappsec/assets/126462046/0355e191-a87e-457b-a631-526bdd6773d2)
To resolve this, you can consider two options:
- [Create an exception](https://docs.openappsec.io/how-to/setup-custom-rules-and-exceptions) for your Dev IP for an immediate fix.
- Lower the minimum to 1, which will require some learning but will happen quickly.

Please keep us updated on your deployment status so that we can assist further if needed.

Best regards,

Oriane
